<?php
/**
 *  JotForm Customer Management Page
 * @category
 * @package
 * @author
 * @license
 * @link
 */
    require "incs/header.php";
    require "helper.php";
    require "customerTable.php";
    
    error_reporting(E_ALL ^ E_NOTICE && E_DEPRECATED);
    
    $apiKey = $_POST['apiKey'];    // get form id's and API key from formPicker.html
    $formIds = explode(',', $_POST['idArray']);    //get idArray as an array NOT a string
    $formTitles = explode(',', $_POST['formTitle']); //get form titles as an array NOT a string
    
    $forms = array_combine_($formIds, $formTitles);

    //make an empty $result array and curl initialization
    $result = [];
    $ch = curl_init();

    // get the all submissions from all selected forms -->
    // (Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/)
foreach ($formIds as $value) {
    curl_setopt($ch, CURLOPT_URL, 'https://api.jotform.com/form/'.$value.'/submissions?apiKey='.$apiKey);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $result[] = json_decode(curl_exec($ch));
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
}

    curl_close($ch);
    $totalProductNum = [];
foreach ($result as $formNum => $form) {
    $content = $form -> content;
    global $paymentMethodOfForm;
    $totalProductNumber = 0;
    foreach ($content as $submissionNum => $submission) {
        $id = $submission-> id;
        $ip = $submission -> ip;
        $formId = $submission -> form_id;
        $createdAt = $submission -> created_at;
        $updatedAt = $submission -> updated_at;
        $answer = $submission -> answers;
            
        foreach ($answer as $key => $value) {
            $type = $value -> type;

            if (isPayment($type)) {
                $isPayment = substr(isPayment($type), 8);
                $paymentMethodOfForm[] = array($forms[$formId] => $isPayment);
                $products = json_decode(($value -> answer) -> paymentArray);
            }
        }
                
        $totalProductNumber = $totalProductNumber + count($products -> product);
        $values[] = array(
            'ip' => $ip,
            'formId' => $formId,
            'formTitle' => $forms[$formId],
            'createdAt' => $createdAt,
            'updatedAt' => $updatedAt,
            'paymentMethod' => $isPayment,
            'products' => ($products -> product),
            'total' => $products -> total,
            'currency' => get_currency_symbol($products -> currency));
            
        foreach ($answer as $key => $value) {
            $type = $value -> type;
                
            if ($type == 'control_email') {
                if (!empty($value -> answer)) {
                    $keys[] = $value -> answer;
                }
            }
        }
    }
    $totalProductNum[] = $totalProductNumber;
}

    $new = [];
for ($i = 0; $i < count($paymentMethodOfForm); $i++) {
    $new = $new + $paymentMethodOfForm[$i];
}
    $paymentMethodArray = $new;

    $allCustomers = array_combine_($keys, $values);
    
    customerTable($allCustomers);

require "incs/footer.php";
